# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31db6f0ce773905e983b412f775a12b9be6f9fd53c47aa572f11d49ad40e7b77925cae58b2ffee45892f5249811dd40f70360d1d5258eb3e094d5aff69a44934

test:
  secret_key_base: 73daa4e6df7d004856ae450e4df24e8a31a3d82c848129528bfb16deb934d5389ae469c9b654aa63b4b9a759fa6c755c27d48b6ab1b9e237843dc2528d4652c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
